# docker-compose.yml
version: "3.9"

services:
  spark-master:
    image: bitnami/spark:3.5.3
    environment:
      - SPARK_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "7077:7077"   # Spark master
      - "8080:8080"   # Spark master UI
    networks: [tfxnet]

  spark-worker:
    image: bitnami/spark:3.5.3
    depends_on: [spark-master]
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=2
      - ALLOW_EMPTY_PASSWORD=yes
    networks: [tfxnet]

  # Apache Beam Spark JobServer for PortableRunner jobs
  beam-jobserver:
    image: apache/beam_spark3_job_server:2.59.0
    depends_on: [spark-master]
    command: ["--spark-master-url=spark://spark-master:7077", "--artifacts-dir=/opt/beam/artifacts"]
    ports:
      - "8099:8099"   # Beam job endpoint
    networks: [tfxnet]
    volumes:
      - beam_artifacts:/opt/beam/artifacts

  mongodb:
    image: mongo:6.0
    networks: [tfxnet]
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  schema-registry:
    build: ./schema-registry
    depends_on: [mongodb]
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - MONGO_DB=schema_db
      - MONGO_COLLECTION=schemas
    networks: [tfxnet]
    ports:
      - "8088:8080"

  # TensorFlow Serving reads model versions written by Pusher
  tf-serving:
    image: tensorflow/serving:2.16.1
    depends_on: [tfx-notebook]
    environment:
      - MODEL_NAME=my_model
    command: ["/usr/bin/tensorflow_model_server",
              "--rest_api_port=8501",
              "--model_name=my_model",
              "--model_base_path=/artifacts/serving/my_model"]
    ports:
      - "8501:8501"
    networks: [tfxnet]
    volumes:
      - artifacts:/artifacts:ro

  tfx-notebook:
    build: ./tfx-notebook
    container_name: tfx-notebook
    ports:
      - "8888:8888"   # Jupyter
    command:
      - jupyter
      - lab
      - --ServerApp.ip=0.0.0.0
      - --ServerApp.port=8888
      - --ServerApp.token=
      - --ServerApp.password=
      - --ServerApp.root_dir=/workspace
      - --no-browser
      - --allow-root
    environment:
      - PYTHONIOENCODING=utf-8
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    volumes:
      - ./notebooks:/workspace
      - ./pipeline:/workspace/pipeline
      - ./data:/data
      - ./artifacts:/artifacts
      - ./metadata:/metadata
    networks: [tfxnet]
  tensorboard:
    build: ./tfx-tensorboard    # folder containing the Dockerfile above
    ports:
      - "6006:6006"
    networks: [tfxnet]
    volumes:
      - ./artifacts:/artifacts
    depends_on: [tfx-notebook]

volumes:
  artifacts:
  metadata:
  beam_artifacts:
  mongo_data:

networks:
  tfxnet:
